name: Build Marlin Firmware

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install Python & PlatformIO
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - run: |
          python -m pip install --upgrade pip
          pip install platformio

      - name: Build for SKR Mini E3 V3.0
        run: |
          cd Marlin
          pio run -e BIGTREE_SKR_MINI_E3_V3_0

      - name: Upload firmware.bin as artifact
        uses: actions/upload-artifact@v2
        with:
          name: marlin-firmware
          path: Marlin/.pio/build/BIGTREE_SKR_MINI_E3_V3_0/firmware.bin
